INSERT INTO breed_dog( id, breed_id,name,name_es,bred_for,bred_for_es,breed_group,breed_group_es,life_span,temperament,temperament_es,origin,weight,height,date,reference_image_id,path_image,creator_id) VALUES

(null,'1','Affenpinscher','Affenpinscher','Small rodent hunting - lapdog','Small rodent hunting - lapdog','Toy','Toy','10 - 12 years','Stubborn - Curious - Playful - Adventurous - Active - Fun-loving','Stubborn - Curious - Playful - Adventurous - Active - Fun-loving','Germany - France','{"metric":"3 - 6","imperial":"6 - 13"}','{"metric":"23 - 29","imperial":"9 - 11.5"}','','BJa4kxc4X','images-list-dogs\Affenpinscher.jpg','1'),

(null,'2','Afghan Hound','Afghan Hound','Coursing and hunting','Coursing and hunting','Hound','Hound','10 - 13 years','Aloof - Clownish - Dignified - Independent - Happy','Aloof - Clownish - Dignified - Independent - Happy','Afghanistan - Iran - Pakistan','{"metric":"23 - 27","imperial":"50 - 60"}','{"metric":"64 - 69","imperial":"25 - 27"}','','hMyT4CDXR','images-list-dogs\Afghan-Hound.jpg','1'),

(null,'3','African Hunting Dog','African Hunting Dog','A wild pack animal','A wild pack animal','','','11 years','Wild - Hardworking - Dutiful','Wild - Hardworking - Dutiful','','{"metric":"20 - 30","imperial":"44 - 66"}','{"metric":"76","imperial":"30"}','','rkiByec47','images-list-dogs\African-Hunting-Dog.jpg','1'),

(null,'4','Airedale Terrier','Airedale Terrier','Badger - otter hunting','Badger - otter hunting','Terrier','Terrier','10 - 13 years','Outgoing - Friendly - Alert - Confident - Intelligent - Courageous','Outgoing - Friendly - Alert - Confident - Intelligent - Courageous','United Kingdom - England','{"metric":"18 - 29","imperial":"40 - 65"}','{"metric":"53 - 58","imperial":"21 - 23"}','','1-7cgoZSh','images-list-dogs\Airedale-Terrier.jpg','1'),

(null,'5','Akbash Dog','Akbash Dog','Sheep guarding','Sheep guarding','Working','Working','10 - 12 years','Loyal - Independent - Intelligent - Brave','Loyal - Independent - Intelligent - Brave','','{"metric":"41 - 54","imperial":"90 - 120"}','{"metric":"71 - 86","imperial":"28 - 34"}','','26pHT3Qk7','images-list-dogs\Akbash-Dog.jpg','1'),

(null,'6','Akita','Akita','Hunting bears','Hunting bears','Working','Working','10 - 14 years','Docile - Alert - Responsive - Dignified - Composed - Friendly - Receptive - Faithful - Courageous','Docile - Alert - Responsive - Dignified - Composed - Friendly - Receptive - Faithful - Courageous','','{"metric":"29 - 52","imperial":"65 - 115"}','{"metric":"61 - 71","imperial":"24 - 28"}','','BFRYBufpm','images-list-dogs\Akita.jpg','1'),

(null,'7','Alapaha Blue Blood Bulldog','Alapaha Blue Blood Bulldog','Guarding','Guarding','Mixed','Mixed','12 - 13 years','Loving - Protective - Trainable - Dutiful - Responsible','Loving - Protective - Trainable - Dutiful - Responsible','','{"metric":"25 - 41","imperial":"55 - 90"}','{"metric":"46 - 61","imperial":"18 - 24"}','','33mJ-V3RX','images-list-dogs\Alapaha-Blue-Blood-Bulldog.jpg','1'),

(null,'8','Alaskan Husky','Alaskan Husky','Sled pulling','Sled pulling','Mixed','Mixed','10 - 13 years','Friendly - Energetic - Loyal - Gentle - Confident','Friendly - Energetic - Loyal - Gentle - Confident','','{"metric":"17 - 23","imperial":"38 - 50"}','{"metric":"58 - 66","imperial":"23 - 26"}','','-HgpNnGXl','images-list-dogs\Alaskan-Husky.jpg','1'),

(null,'9','Alaskan Malamute','Alaskan Malamute','Hauling heavy freight - Sled pulling','Hauling heavy freight - Sled pulling','Working','Working','12 - 15 years','Friendly - Affectionate - Devoted - Loyal - Dignified - Playful','Friendly - Affectionate - Devoted - Loyal - Dignified - Playful','','{"metric":"29 - 45","imperial":"65 - 100"}','{"metric":"58 - 64","imperial":"23 - 25"}','','dW5UucTIW','images-list-dogs\Alaskan-Malamute.jpg','1'),

(null,'10','American Bulldog','American Bulldog','','','Working','Working','10 - 12 years','Friendly - Assertive - Energetic - Loyal - Gentle - Confident - Dominant','Friendly - Assertive - Energetic - Loyal - Gentle - Confident - Dominant','','{"metric":"27 - 54","imperial":"60 - 120"}','{"metric":"56 - 69","imperial":"22 - 27"}','','pk1AAdloG','images-list-dogs\American-Bulldog.jpg','1'),

(null,'11','American Bully','American Bully','Family companion dog','Family companion dog','','','8 – 15 years','Strong Willed - Stubborn - Friendly - Clownish - Affectionate - Loyal - Obedient - Intelligent - Courageous','Strong Willed - Stubborn - Friendly - Clownish - Affectionate - Loyal - Obedient - Intelligent - Courageous','','{"metric":"14 - 68","imperial":"30 - 150"}','{"metric":"36 - 43","imperial":"14 - 17"}','','sqQJDtbpY','images-list-dogs\American-Bully.jpg','1'),

(null,'12','American Eskimo Dog','American Eskimo Dog','Circus performer','Circus performer','Non-Sporting','Non-Sporting','12 - 15 years','Friendly - Alert - Reserved - Intelligent - Protective','Friendly - Alert - Reserved - Intelligent - Protective','','{"metric":"9 - 18","imperial":"20 - 40"}','{"metric":"38 - 48","imperial":"15 - 19"}','','Bymjyec4m','images-list-dogs\American-Eskimo-Dog.jpg','1'),

(null,'13','American Eskimo Dog  -Miniature-','American Eskimo Dog  -Miniature-','Companionship','Companionship','','','13 – 15 years','Friendly - Alert - Reserved - Intelligent - Protective','Friendly - Alert - Reserved - Intelligent - Protective','','{"metric":"3 - 5","imperial":"7 - 10"}','{"metric":"23 - 30","imperial":"9 - 12"}','','_gn8GLrE6','images-list-dogs\American-Eskimo-Dog---Miniature-.jpg','1'),

(null,'14','American Foxhound','American Foxhound','Fox hunting - scent hound','Fox hunting - scent hound','Hound','Hound','8 - 15 years','Kind - Sweet-Tempered - Loyal - Independent - Intelligent - Loving','Kind - Sweet-Tempered - Loyal - Independent - Intelligent - Loving','','{"metric":"29 - 34","imperial":"65 - 75"}','{"metric":"53 - 71","imperial":"21 - 28"}','','S14n1x9NQ','images-list-dogs\American-Foxhound.jpg','1'),

(null,'15','American Pit Bull Terrier','American Pit Bull Terrier','Fighting','Fighting','Terrier','Terrier','10 - 15 years','Strong Willed - Stubborn - Friendly - Clownish - Affectionate - Loyal - Obedient - Intelligent - Courageous','Strong Willed - Stubborn - Friendly - Clownish - Affectionate - Loyal - Obedient - Intelligent - Courageous','','{"metric":"14 - 27","imperial":"30 - 60"}','{"metric":"43 - 53","imperial":"17 - 21"}','','HkC31gcNm','images-list-dogs\American-Pit-Bull-Terrier.jpg','1'),

(null,'16','American Staffordshire Terrier','American Staffordshire Terrier','','','Terrier','Terrier','12 - 15 years','Tenacious - Friendly - Devoted - Loyal - Attentive - Courageous','Tenacious - Friendly - Devoted - Loyal - Attentive - Courageous','','{"metric":"23 - 27","imperial":"50 - 60"}','{"metric":"43 - 48","imperial":"17 - 19"}','','rJIakgc4m','images-list-dogs\American-Staffordshire-Terrier.jpg','1'),

(null,'17','American Water Spaniel','American Water Spaniel','Bird flushing and retrieving','Bird flushing and retrieving','Sporting','Sporting','10 - 12 years','Friendly - Energetic - Obedient - Intelligent - Protective - Trainable','Friendly - Energetic - Obedient - Intelligent - Protective - Trainable','','{"metric":"11 - 20","imperial":"25 - 45"}','{"metric":"38 - 46","imperial":"15 - 18"}','','SkmRJl9VQ','images-list-dogs\American-Water-Spaniel.jpg','1'),

(null,'18','Anatolian Shepherd Dog','Anatolian Shepherd Dog','Livestock herding','Livestock herding','Working','Working','11 - 13 years','Steady - Bold - Independent - Confident - Intelligent - Proud','Steady - Bold - Independent - Confident - Intelligent - Proud','','{"metric":"36 - 68","imperial":"80 - 150"}','{"metric":"69 - 74","imperial":"27 - 29"}','','BJT0Jx5Nm','images-list-dogs\Anatolian-Shepherd-Dog.jpg','1'),

(null,'19','Appenzeller Sennenhund','Appenzeller Sennenhund','Herding livestock - pulling carts - and guarding the farm','Herding livestock - pulling carts - and guarding the farm','','','12 – 14 years','Reliable - Fearless - Energetic - Lively - Self-assured','Reliable - Fearless - Energetic - Lively - Self-assured','','{"metric":"22 - 25","imperial":"48 - 55"}','{"metric":"51 - 56","imperial":"20 - 22"}','','HkNkxlqEX','images-list-dogs\Appenzeller-Sennenhund.jpg','1'),

(null,'21','Australian Cattle Dog','Australian Cattle Dog','Cattle herding - herding trials','Cattle herding - herding trials','Herding','Herding','12 - 14 years','Cautious - Energetic - Loyal - Obedient - Protective - Brave','Cautious - Energetic - Loyal - Obedient - Protective - Brave','','{"metric":"20 - 28","imperial":"44 - 62"}','{"metric":"43 - 51","imperial":"17 - 20"}','','IBkYVm4v1','images-list-dogs\Australian-Cattle-Dog.jpg','1'),

(null,'22','Australian Kelpie','Australian Kelpie','Farm dog - Cattle herding','Farm dog - Cattle herding','Herding','Herding','10 - 13 years','Friendly - Energetic - Alert - Loyal - Intelligent - Eager','Friendly - Energetic - Alert - Loyal - Intelligent - Eager','','{"metric":"14 - 21","imperial":"31 - 46"}','{"metric":"43 - 51","imperial":"17 - 20"}','','Hyq1ge9VQ','images-list-dogs\Australian-Kelpie.jpg','1'),

(null,'23','Australian Shepherd','Australian Shepherd','Sheep herding','Sheep herding','Herding','Herding','12 - 16 years','Good-natured - Affectionate - Intelligent - Active - Protective','Good-natured - Affectionate - Intelligent - Active - Protective','','{"metric":"16 - 29","imperial":"35 - 65"}','{"metric":"46 - 58","imperial":"18 - 23"}','','B1-llgq4m','images-list-dogs\Australian-Shepherd.jpg','1'),

(null,'24','Australian Terrier','Australian Terrier','Cattle herdering - hunting snakes and rodents','Cattle herdering - hunting snakes and rodents','Terrier','Terrier','15 years','Spirited - Alert - Loyal - Companionable - Even Tempered - Courageous','Spirited - Alert - Loyal - Companionable - Even Tempered - Courageous','','{"metric":"6 - 7","imperial":"14 - 16"}','{"metric":"25 - 28","imperial":"10 - 11"}','','r1Ylge5Vm','images-list-dogs\Australian-Terrier.jpg','1'),

(null,'25','Azawakh','Azawakh','Livestock guardian - hunting','Livestock guardian - hunting','Hound','Hound','10 - 13 years','Aloof - Affectionate - Attentive - Rugged - Fierce - Refined','Aloof - Affectionate - Attentive - Rugged - Fierce - Refined','','{"metric":"15 - 25","imperial":"33 - 55"}','{"metric":"58 - 74","imperial":"23 - 29"}','','SkvZgx94m','images-list-dogs\Azawakh.jpg','1'),

(null,'26','Barbet','Barbet','Hunting water game','Hunting water game','','','13 – 15 years','Obedient - Companionable - Intelligent - Joyful','Obedient - Companionable - Intelligent - Joyful','','{"metric":"18 - 29","imperial":"40 - 65"}','{"metric":"51 - 66","imperial":"20 - 26"}','','HyWGexcVQ','images-list-dogs\Barbet.jpg','1'),

(null,'28','Basenji','Basenji','Hunting','Hunting','Hound','Hound','10 - 12 years','Affectionate - Energetic - Alert - Curious - Playful - Intelligent','Affectionate - Energetic - Alert - Curious - Playful - Intelligent','','{"metric":"10 - 11","imperial":"22 - 24"}','{"metric":"41 - 43","imperial":"16 - 17"}','','H1dGlxqNQ','images-list-dogs\Basenji.jpg','1'),

(null,'29','Basset Bleu de Gascogne','Basset Bleu de Gascogne','Hunting on foot.','Hunting on foot.','Hound','Hound','10 - 14 years','Affectionate - Lively - Agile - Curious - Happy - Active','Affectionate - Lively - Agile - Curious - Happy - Active','','{"metric":"16 - 18","imperial":"35 - 40"}','{"metric":"33 - 38","imperial":"13 - 15"}','','BkMQll94X','images-list-dogs\Basset-Bleu-de-Gascogne.jpg','1'),

(null,'30','Basset Hound','Basset Hound','Hunting by scent','Hunting by scent','Hound','Hound','12 - 15 years','Tenacious - Friendly - Affectionate - Devoted - Sweet-Tempered - Gentle','Tenacious - Friendly - Affectionate - Devoted - Sweet-Tempered - Gentle','','{"metric":"23 - 29","imperial":"50 - 65"}','{"metric":"36","imperial":"14"}','','Sy57xx9EX','images-list-dogs\Basset-Hound.jpg','1'),

(null,'31','Beagle','Beagle','Rabbit - hare hunting','Rabbit - hare hunting','Hound','Hound','13 - 16 years','Amiable - Even Tempered - Excitable - Determined - Gentle - Intelligent','Amiable - Even Tempered - Excitable - Determined - Gentle - Intelligent','','{"metric":"9 - 16","imperial":"20 - 35"}','{"metric":"33 - 38","imperial":"13 - 15"}','','Syd4xxqEm','images-list-dogs\Beagle.jpg','1'),

(null,'32','Bearded Collie','Bearded Collie','Sheep herding','Sheep herding','Herding','Herding','12 - 14 years','Self-confidence - Hardy - Lively - Alert - Intelligent - Active','Self-confidence - Hardy - Lively - Alert - Intelligent - Active','','{"metric":"20 - 25","imperial":"45 - 55"}','{"metric":"51 - 56","imperial":"20 - 22"}','','A09F4c1qP','images-list-dogs\Bearded-Collie.jpg','1'),

(null,'33','Beauceron','Beauceron','Boar herding - hunting - guarding','Boar herding - hunting - guarding','Herding','Herding','10 - 12 years','Fearless - Friendly - Intelligent - Protective - Calm','Fearless - Friendly - Intelligent - Protective - Calm','','{"metric":"36 - 50","imperial":"80 - 110"}','{"metric":"61 - 70","imperial":"24 - 27.5"}','','HJQ8ge5V7','images-list-dogs\Beauceron.jpg','1'),

(null,'34','Bedlington Terrier','Bedlington Terrier','Killing rat - badger - other vermin','Killing rat - badger - other vermin','Terrier','Terrier','14 - 16 years','Affectionate - Spirited - Intelligent - Good-tempered','Affectionate - Spirited - Intelligent - Good-tempered','','{"metric":"8 - 10","imperial":"17 - 23"}','{"metric":"38 - 41","imperial":"15 - 16"}','','ByK8gx947','images-list-dogs\Bedlington-Terrier.jpg','1'),

(null,'36','Belgian Malinois','Belgian Malinois','Stock herding','Stock herding','Herding','Herding','12 - 14 years','Watchful - Alert - Stubborn - Friendly - Confident - Hard-working - Active - Protective','Watchful - Alert - Stubborn - Friendly - Confident - Hard-working - Active - Protective','','{"metric":"18 - 36","imperial":"40 - 80"}','{"metric":"56 - 66","imperial":"22 - 26"}','','r1f_ll5VX','images-list-dogs\Belgian-Malinois.jpg','1'),

(null,'38','Belgian Tervuren','Belgian Tervuren','Guarding - Drafting - Police work.','Guarding - Drafting - Police work.','Herding','Herding','10 - 12 years','Energetic - Alert - Loyal - Intelligent - Attentive - Protective','Energetic - Alert - Loyal - Intelligent - Attentive - Protective','','{"metric":"18 - 29","imperial":"40 - 65"}','{"metric":"56 - 66","imperial":"22 - 26"}','','B1KdxlcNX','images-list-dogs\Belgian-Tervuren.jpg','1'),

(null,'41','Bernese Mountain Dog','Bernese Mountain Dog','Draft work','Draft work','Working','Working','7 - 10 years','Affectionate - Loyal - Intelligent - Faithful','Affectionate - Loyal - Intelligent - Faithful','','{"metric":"29 - 54","imperial":"65 - 120"}','{"metric":"58 - 70","imperial":"23 - 27.5"}','','S1fFlx5Em','images-list-dogs\Bernese-Mountain-Dog.jpg','1'),

(null,'42','Bichon Frise','Bichon Frise','Companion','Companion','Non-Sporting','Non-Sporting','15 years','Feisty - Affectionate - Cheerful - Playful - Gentle - Sensitive','Feisty - Affectionate - Cheerful - Playful - Gentle - Sensitive','','{"metric":"5 - 8","imperial":"10 - 18"}','{"metric":"24 - 29","imperial":"9.5 - 11.5"}','','HkuYlxqEQ','images-list-dogs\Bichon-Frise.jpg','1'),

(null,'43','Black and Tan Coonhound','Black and Tan Coonhound','Hunting raccoons - night hunting','Hunting raccoons - night hunting','Hound','Hound','10 - 12 years','Easygoing - Gentle - Adaptable - Trusting - Even Tempered - Lovable','Easygoing - Gentle - Adaptable - Trusting - Even Tempered - Lovable','','{"metric":"29 - 45","imperial":"65 - 100"}','{"metric":"58 - 69","imperial":"23 - 27"}','','HJAFgxcNQ','images-list-dogs\Black-and-Tan-Coonhound.jpg','1'),

(null,'45','Bloodhound','Bloodhound','Trailing','Trailing','Hound','Hound','8 - 10 years','Stubborn - Affectionate - Gentle - Even Tempered','Stubborn - Affectionate - Gentle - Even Tempered','','{"metric":"36 - 50","imperial":"80 - 110"}','{"metric":"58 - 69","imperial":"23 - 27"}','','Skdcgx9VX','images-list-dogs\Bloodhound.jpg','1'),

(null,'47','Bluetick Coonhound','Bluetick Coonhound','Hunting with a superior sense of smell.','Hunting with a superior sense of smell.','Hound','Hound','12 - 14 years','Friendly - Intelligent - Active','Friendly - Intelligent - Active','','{"metric":"20 - 36","imperial":"45 - 80"}','{"metric":"53 - 69","imperial":"21 - 27"}','','rJxieg9VQ','images-list-dogs\Bluetick-Coonhound.jpg','1'),

(null,'48','Boerboel','Boerboel','Guarding the homestead - farm work.','Guarding the homestead - farm work.','Working','Working','10 - 12 years','Obedient - Confident - Intelligent - Dominant - Territorial','Obedient - Confident - Intelligent - Dominant - Territorial','','{"metric":"50 - 91","imperial":"110 - 200"}','{"metric":"56 - 69","imperial":"22 - 27"}','','HyOjge5Vm','images-list-dogs\Boerboel.jpg','1'),

(null,'50','Border Collie','Border Collie','Sheep herder','Sheep herder','Herding','Herding','12 - 16 years','Tenacious - Keen - Energetic - Responsive - Alert - Intelligent','Tenacious - Keen - Energetic - Responsive - Alert - Intelligent','','{"metric":"14 - 20","imperial":"30 - 45"}','{"metric":"46 - 56","imperial":"18 - 22"}','','sGQvQUpsp','images-list-dogs\Border-Collie.jpg','1'),

(null,'51','Border Terrier','Border Terrier','Fox bolting - ratting','Fox bolting - ratting','Terrier','Terrier','12 - 14 years','Fearless - Affectionate - Alert - Obedient - Intelligent - Even Tempered','Fearless - Affectionate - Alert - Obedient - Intelligent - Even Tempered','','{"metric":"5 - 7","imperial":"11.5 - 15.5"}','{"metric":"28 - 41","imperial":"11 - 16"}','','HJOpge9Em','images-list-dogs\Border-Terrier.jpg','1'),

(null,'53','Boston Terrier','Boston Terrier','Ratting - Companionship','Ratting - Companionship','Non-Sporting','Non-Sporting','11 - 13 years','Friendly - Lively - Intelligent','Friendly - Lively - Intelligent','','{"metric":"5 - 11","imperial":"10 - 25"}','{"metric":"41 - 43","imperial":"16 - 17"}','','rkZRggqVX','images-list-dogs\Boston-Terrier.jpg','1'),

(null,'54','Bouvier des Flandres','Bouvier des Flandres','Cattle herding','Cattle herding','Herding','Herding','10 - 15 years','Protective - Loyal - Gentle - Intelligent - Familial - Rational','Protective - Loyal - Gentle - Intelligent - Familial - Rational','','{"metric":"32 - 50","imperial":"70 - 110"}','{"metric":"60 - 70","imperial":"23.5 - 27.5"}','','Byd0xl5VX','images-list-dogs\Bouvier-des-Flandres.jpg','1'),

(null,'55','Boxer','Boxer','Bull-baiting - guardian','Bull-baiting - guardian','Working','Working','8 - 10 years','Devoted - Fearless - Friendly - Cheerful - Energetic - Loyal - Playful - Confident - Intelligent - Bright - Brave - Calm','Devoted - Fearless - Friendly - Cheerful - Energetic - Loyal - Playful - Confident - Intelligent - Bright - Brave - Calm','','{"metric":"23 - 32","imperial":"50 - 70"}','{"metric":"55 - 64","imperial":"21.5 - 25"}','','ry1kWe5VQ','images-list-dogs\Boxer.jpg','1'),

(null,'56','Boykin Spaniel','Boykin Spaniel','Turkey retrieving','Turkey retrieving','Sporting','Sporting','10 - 14 years','Friendly - Energetic - Companionable - Intelligent - Eager - Trainable','Friendly - Energetic - Companionable - Intelligent - Eager - Trainable','','{"metric":"11 - 18","imperial":"25 - 40"}','{"metric":"36 - 46","imperial":"14 - 18"}','','ryHJZlcNX','images-list-dogs\Boykin-Spaniel.jpg','1'),

(null,'57','Bracco Italiano','Bracco Italiano','Versatile gun dog','Versatile gun dog','Sporting','Sporting','10 - 12 years','Stubborn - Affectionate - Loyal - Playful - Companionable - Trainable','Stubborn - Affectionate - Loyal - Playful - Companionable - Trainable','','{"metric":"25 - 40","imperial":"55 - 88"}','{"metric":"55 - 67","imperial":"21.5 - 26.5"}','','S13yZg5VQ','images-list-dogs\Bracco-Italiano.jpg','1'),

(null,'58','Briard','Briard','Herding - guarding sheep','Herding - guarding sheep','Herding','Herding','10 - 12 years','Fearless - Loyal - Obedient - Intelligent - Faithful - Protective','Fearless - Loyal - Obedient - Intelligent - Faithful - Protective','','{"metric":"32 - 41","imperial":"70 - 90"}','{"metric":"56 - 69","imperial":"22 - 27"}','','rkVlblcEQ','images-list-dogs\Briard.jpg','1'),

(null,'59','Brittany','Brittany','Pointing - retrieving','Pointing - retrieving','Sporting','Sporting','12 - 14 years','Agile - Adaptable - Quick - Intelligent - Attentive - Happy','Agile - Adaptable - Quick - Intelligent - Attentive - Happy','','{"metric":"14 - 20","imperial":"30 - 45"}','{"metric":"44 - 52","imperial":"17.5 - 20.5"}','','HJWZZxc4X','images-list-dogs\Brittany.jpg','1'),

(null,'61','Bull Terrier','Bull Terrier','Bull baiting - Fighting','Bull baiting - Fighting','Terrier','Terrier','10 - 12 years','Trainable - Protective - Sweet-Tempered - Keen - Active','Trainable - Protective - Sweet-Tempered - Keen - Active','','{"metric":"23 - 32","imperial":"50 - 70"}','{"metric":"53 - 56","imperial":"21 - 22"}','','VSraIEQGd','images-list-dogs\Bull-Terrier.jpg','1'),

(null,'62','Bull Terrier  -Miniature-','Bull Terrier  -Miniature-','An elegant man s fashion statement','An elegant man s fashion statement','','','11 – 14 years','Trainable - Protective - Sweet-Tempered - Keen - Active - Territorial','Trainable - Protective - Sweet-Tempered - Keen - Active - Territorial','','{"metric":"11 - 15","imperial":"25 - 33"}','{"metric":"25 - 36","imperial":"10 - 14"}','','BkKZWlcVX','images-list-dogs\Bull-Terrier---Miniature-.jpg','1'),

(null,'64','Bullmastiff','Bullmastiff','Estate guardian','Estate guardian','Working','Working','8 - 12 years','Docile - Reliable - Devoted - Alert - Loyal - Reserved - Loving - Protective - Powerful - Calm - Courageous','Docile - Reliable - Devoted - Alert - Loyal - Reserved - Loving - Protective - Powerful - Calm - Courageous','','{"metric":"45 - 59","imperial":"100 - 130"}','{"metric":"61 - 69","imperial":"24 - 27"}','','r1ifZl5E7','images-list-dogs\Bullmastiff.jpg','1'),

(null,'65','Cairn Terrier','Cairn Terrier','Bolting of otter - foxes - other vermin','Bolting of otter - foxes - other vermin','Terrier','Terrier','14 - 15 years','Hardy - Fearless - Assertive - Gay - Intelligent - Active','Hardy - Fearless - Assertive - Gay - Intelligent - Active','','{"metric":"6 - 6","imperial":"13 - 14"}','{"metric":"23 - 25","imperial":"9 - 10"}','','Sk7Qbg9E7','images-list-dogs\Cairn-Terrier.jpg','1'),

(null,'67','Cane Corso','Cane Corso','Companion - guard dog - and hunter','Companion - guard dog - and hunter','Working','Working','10 - 11 years','Trainable - Reserved - Stable - Quiet - Even Tempered - Calm','Trainable - Reserved - Stable - Quiet - Even Tempered - Calm','','{"metric":"40 - 54","imperial":"88 - 120"}','{"metric":"60 - 70","imperial":"23.5 - 27.5"}','','r15m-lc4m','images-list-dogs\Cane-Corso.jpg','1'),

(null,'68','Cardigan Welsh Corgi','Cardigan Welsh Corgi','Cattle droving','Cattle droving','Herding','Herding','12 - 14 years','Affectionate - Devoted - Alert - Companionable - Intelligent - Active','Affectionate - Devoted - Alert - Companionable - Intelligent - Active','','{"metric":"11 - 17","imperial":"25 - 38"}','{"metric":"27 - 32","imperial":"10.5 - 12.5"}','','SyXN-e9NX','images-list-dogs\Cardigan-Welsh-Corgi.jpg','1'),

(null,'69','Catahoula Leopard Dog','Catahoula Leopard Dog','Driving livestock','Driving livestock','Herding','Herding','10 - 12 years','Energetic - Inquisitive - Independent - Gentle - Intelligent - Loving','Energetic - Inquisitive - Independent - Gentle - Intelligent - Loving','','{"metric":"23 - 43","imperial":"50 - 95"}','{"metric":"51 - 66","imperial":"20 - 26"}','','BJcNbec4X','images-list-dogs\Catahoula-Leopard-Dog.jpg','1'),

(null,'70','Caucasian Shepherd  -Ovcharka-','Caucasian Shepherd  -Ovcharka-','Guard dogs - defending sheep from predators - mainly wolves - jackals and bears','Guard dogs - defending sheep from predators - mainly wolves - jackals and bears','Working','Working','10 - 12 years','Alert - Quick - Dominant - Powerful - Calm - Strong','Alert - Quick - Dominant - Powerful - Calm - Strong','','{"metric":"36 - 45","imperial":"80 - 100"}','{"metric":"61 - 85","imperial":"24 - 33.5"}','','r1rrWe5Em','images-list-dogs\Caucasian-Shepherd---Ovcharka-.jpg','1'),

(null,'71','Cavalier King Charles Spaniel','Cavalier King Charles Spaniel','Flushing small birds - companion','Flushing small birds - companion','Toy','Toy','10 - 14 years','Fearless - Affectionate - Sociable - Patient - Playful - Adaptable','Fearless - Affectionate - Sociable - Patient - Playful - Adaptable','','{"metric":"6 - 8","imperial":"13 - 18"}','{"metric":"30 - 33","imperial":"12 - 13"}','','HJRBbe94Q','images-list-dogs\Cavalier-King-Charles-Spaniel.jpg','1'),

(null,'76','Chesapeake Bay Retriever','Chesapeake Bay Retriever','Water Retriever','Water Retriever','Sporting','Sporting','10 - 13 years','Affectionate - Intelligent - Quiet - Dominant - Happy - Protective','Affectionate - Intelligent - Quiet - Dominant - Happy - Protective','','{"metric":"25 - 36","imperial":"55 - 80"}','{"metric":"53 - 66","imperial":"21 - 26"}','','9BXwUeCc2','images-list-dogs\Chesapeake-Bay-Retriever.jpg','1'),

(null,'78','Chinese Crested','Chinese Crested','Ratting - lapdog - curio','Ratting - lapdog - curio','Toy','Toy','10 - 14 years','Affectionate - Sweet-Tempered - Lively - Alert - Playful - Happy','Affectionate - Sweet-Tempered - Lively - Alert - Playful - Happy','','{"metric":"5 - 6","imperial":"10 - 13"}','{"metric":"28 - 33","imperial":"11 - 13"}','','B1pDZx9Nm','images-list-dogs\Chinese-Crested.jpg','1'),

(null,'79','Chinese Shar-Pei','Chinese Shar-Pei','Fighting','Fighting','Non-Sporting','Non-Sporting','10 years','Suspicious - Affectionate - Devoted - Reserved - Independent - Loving','Suspicious - Affectionate - Devoted - Reserved - Independent - Loving','','{"metric":"20 - 27","imperial":"45 - 60"}','{"metric":"46 - 51","imperial":"18 - 20"}','','B1ruWl94Q','images-list-dogs\Chinese-Shar-Pei.jpg','1'),

(null,'80','Chinook','Chinook','Sled pulling','Sled pulling','Working','Working','12 - 15 years','Friendly - Alert - Dignified - Intelligent - Calm','Friendly - Alert - Dignified - Intelligent - Calm','','{"metric":"23 - 41","imperial":"50 - 90"}','{"metric":"56 - 66","imperial":"22 - 26"}','','Sypubg54Q','images-list-dogs\Chinook.jpg','1'),

(null,'81','Chow Chow','Chow Chow','Guardian - cart pulling - hunting','Guardian - cart pulling - hunting','Non-Sporting','Non-Sporting','12 - 15 years','Aloof - Loyal - Independent - Quiet','Aloof - Loyal - Independent - Quiet','','{"metric":"18 - 32","imperial":"40 - 70"}','{"metric":"43 - 51","imperial":"17 - 20"}','','ry8KWgqEQ','images-list-dogs\Chow-Chow.jpg','1'),

(null,'84','Clumber Spaniel','Clumber Spaniel','Bird flushing - retrieving','Bird flushing - retrieving','Sporting','Sporting','10 - 12 years','Affectionate - Loyal - Dignified - Gentle - Calm - Great-hearted','Affectionate - Loyal - Dignified - Gentle - Calm - Great-hearted','','{"metric":"25 - 39","imperial":"55 - 85"}','{"metric":"43 - 51","imperial":"17 - 20"}','','rkeqWgq4Q','images-list-dogs\Clumber-Spaniel.jpg','1'),

(null,'86','Cocker Spaniel','Cocker Spaniel','Bird flushing - retrieving','Bird flushing - retrieving','Sporting','Sporting','12 - 15 years','Trainable - Friendly - Affectionate - Playful - Quiet - Faithful','Trainable - Friendly - Affectionate - Playful - Quiet - Faithful','','{"metric":"9 - 14","imperial":"20 - 30"}','{"metric":"36 - 38","imperial":"14 - 15"}','','1lFmrzECl','images-list-dogs\Cocker-Spaniel.jpg','1'),

(null,'87','Cocker Spaniel  -American-','Cocker Spaniel  -American-','Hunting the American woodcock','Hunting the American woodcock','Sporting','Sporting','12 - 15 years','Outgoing - Sociable - Trusting - Joyful - Even Tempered - Merry','Outgoing - Sociable - Trusting - Joyful - Even Tempered - Merry','','{"metric":"9 - 14","imperial":"20 - 30"}','{"metric":"36 - 38","imperial":"14 - 15"}','','HkRcZe547','images-list-dogs\Cocker-Spaniel---American-.jpg','1'),

(null,'89','Coton de Tulear','Coton de Tulear','Accompanying ladies on long sea voyages - ratters onboard ship.','Accompanying ladies on long sea voyages - ratters onboard ship.','Non-Sporting','Non-Sporting','13 - 16 years','Affectionate - Lively - Playful - Intelligent - Trainable - Vocal','Affectionate - Lively - Playful - Intelligent - Trainable - Vocal','','{"metric":"4 - 7","imperial":"9 - 15"}','{"metric":"23 - 28","imperial":"9 - 11"}','','SyviZlqNm','images-list-dogs\Coton-de-Tulear.jpg','1'),

(null,'92','Dalmatian','Dalmatian','Carriage dog - trot alongside carriages to protect the occupants from banditry or other interference','Carriage dog - trot alongside carriages to protect the occupants from banditry or other interference','Non-Sporting','Non-Sporting','10 - 13 years','Outgoing - Friendly - Energetic - Playful - Sensitive - Intelligent - Active','Outgoing - Friendly - Energetic - Playful - Sensitive - Intelligent - Active','','{"metric":"23 - 25","imperial":"50 - 55"}','{"metric":"48 - 58","imperial":"19 - 23"}','','SkJ3blcN7','images-list-dogs\Dalmatian.jpg','1'),

(null,'94','Doberman Pinscher','Doberman Pinscher','Guardian','Guardian','Working','Working','10 years','Fearless - Energetic - Alert - Loyal - Obedient - Confident - Intelligent','Fearless - Energetic - Alert - Loyal - Obedient - Confident - Intelligent','','{"metric":"30 - 40","imperial":"66 - 88"}','{"metric":"61 - 71","imperial":"24 - 28"}','','HyL3bl94Q','images-list-dogs\Doberman-Pinscher.jpg','1'),

(null,'95','Dogo Argentino','Dogo Argentino','Big-game hunting','Big-game hunting','Working','Working','10 - 12 years','Friendly - Affectionate - Cheerful - Loyal - Tolerant - Protective','Friendly - Affectionate - Cheerful - Loyal - Tolerant - Protective','','{"metric":"36 - 45","imperial":"80 - 100"}','{"metric":"60 - 69","imperial":"23.5 - 27"}','','S1nhWx94Q','images-list-dogs\Dogo-Argentino.jpg','1'),

(null,'98','Dutch Shepherd','Dutch Shepherd','Farms - watchdog - guard duty','Farms - watchdog - guard duty','','','15 years','Reliable - Affectionate - Alert - Loyal - Obedient - Trainable','Reliable - Affectionate - Alert - Loyal - Obedient - Trainable','','{"metric":"23 - 32","imperial":"50 - 70"}','{"metric":"56 - 62","imperial":"22 - 24.5"}','','BkE6Wg5E7','images-list-dogs\Dutch-Shepherd.jpg','1'),

(null,'101','English Setter','English Setter','Bird setting - retrieving','Bird setting - retrieving','Sporting','Sporting','12 years','Strong Willed - Mischievous - Affectionate - Energetic - Playful - Companionable - Gentle - Hard-working - Intelligent - Eager - People-Oriented','Strong Willed - Mischievous - Affectionate - Energetic - Playful - Companionable - Gentle - Hard-working - Intelligent - Eager - People-Oriented','','{"metric":"20 - 36","imperial":"45 - 80"}','{"metric":"61 - 64","imperial":"24 - 25"}','','By4A-eqVX','images-list-dogs\English-Setter.jpg','1'),

(null,'102','English Shepherd','English Shepherd','Herding & guarding livestock - farm watch dog','Herding & guarding livestock - farm watch dog','Working','Working','10 - 13 years','Kind - Energetic - Independent - Adaptable - Intelligent - Bossy','Kind - Energetic - Independent - Adaptable - Intelligent - Bossy','','{"metric":"20 - 30","imperial":"44 - 66"}','{"metric":"46 - 58","imperial":"18 - 23"}','','H1QyMe5EQ','images-list-dogs\English-Shepherd.jpg','1'),

(null,'103','English Springer Spaniel','English Springer Spaniel','Bird flushing - retrieving','Bird flushing - retrieving','Sporting','Sporting','12 - 14 years','Affectionate - Cheerful - Alert - Intelligent - Attentive - Active','Affectionate - Cheerful - Alert - Intelligent - Attentive - Active','','{"metric":"16 - 23","imperial":"35 - 50"}','{"metric":"48 - 51","imperial":"19 - 20"}','','Hk0Jfe5VQ','images-list-dogs\English-Springer-Spaniel.jpg','1'),

(null,'104','English Toy Spaniel','English Toy Spaniel','Companion of kings','Companion of kings','Toy','Toy','10 - 12 years','Affectionate - Reserved - Playful - Gentle - Happy - Loving','Affectionate - Reserved - Playful - Gentle - Happy - Loving','','{"metric":"4 - 6","imperial":"8 - 14"}','{"metric":"25","imperial":"10"}','','SkIgzxqNQ','images-list-dogs\English-Toy-Spaniel.jpg','1'),

(null,'105','English Toy Terrier','English Toy Terrier','Rat-baiting','Rat-baiting','','','12 - 13 years','Stubborn - Alert - Companionable - Intelligent - Cunning - Trainable','Stubborn - Alert - Companionable - Intelligent - Cunning - Trainable','','{"metric":"3 - 4","imperial":"6 - 8"}','{"metric":"25 - 30","imperial":"10 - 12"}','','SJ6eMxqEQ','images-list-dogs\English-Toy-Terrier.jpg','1'),

(null,'107','Eurasier','Eurasier','Companionship','Companionship','Non-Sporting','Non-Sporting','12 - 14 years','Alert - Reserved - Intelligent - Even Tempered - Watchful - Calm','Alert - Reserved - Intelligent - Even Tempered - Watchful - Calm','','{"metric":"18 - 32","imperial":"40 - 70"}','{"metric":"52 - 60","imperial":"20.5 - 23.5"}','','S1VWGx9Nm','images-list-dogs\Eurasier.jpg','1'),

(null,'108','Field Spaniel','Field Spaniel','Bird flushing - retrieving','Bird flushing - retrieving','Sporting','Sporting','11 - 15 years','Docile - Cautious - Sociable - Sensitive - Adaptable - Familial','Docile - Cautious - Sociable - Sensitive - Adaptable - Familial','','{"metric":"16 - 23","imperial":"35 - 50"}','{"metric":"43 - 46","imperial":"17 - 18"}','','SkJfGecE7','images-list-dogs\Field-Spaniel.jpg','1'),

(null,'110','Finnish Lapphund','Finnish Lapphund','Herding reindeer','Herding reindeer','Herding','Herding','12 - 15 years','Friendly - Keen - Faithful - Calm - Courageous','Friendly - Keen - Faithful - Calm - Courageous','','{"metric":"15 - 24","imperial":"33 - 53"}','{"metric":"41 - 53","imperial":"16 - 21"}','','S1KMGg5Vm','images-list-dogs\Finnish-Lapphund.jpg','1'),

(null,'111','Finnish Spitz','Finnish Spitz','Hunting birds - small mammals','Hunting birds - small mammals','Non-Sporting','Non-Sporting','12 - 15 years','Playful - Loyal - Independent - Intelligent - Happy - Vocal','Playful - Loyal - Independent - Intelligent - Happy - Vocal','','{"metric":"10 - 13","imperial":"23 - 28"}','{"metric":"39 - 51","imperial":"15.5 - 20"}','','3PjHlQbkV','images-list-dogs\Finnish-Spitz.jpg','1'),

(null,'113','French Bulldog','French Bulldog','Lapdog','Lapdog','Non-Sporting','Non-Sporting','9 - 11 years','Playful - Affectionate - Keen - Sociable - Lively - Alert - Easygoing - Patient - Athletic - Bright','Playful - Affectionate - Keen - Sociable - Lively - Alert - Easygoing - Patient - Athletic - Bright','','{"metric":"13","imperial":"28"}','{"metric":"28 - 30","imperial":"11 - 12"}','','HyWNfxc47','images-list-dogs\French-Bulldog.jpg','1'),

(null,'114','German Pinscher','German Pinscher','Watchdog - Hunting vermin on the farm.','Watchdog - Hunting vermin on the farm.','Working','Working','12 - 14 years','Spirited - Lively - Intelligent - Loving - Even Tempered - Familial','Spirited - Lively - Intelligent - Loving - Even Tempered - Familial','','{"metric":"11 - 20","imperial":"25 - 45"}','{"metric":"43 - 51","imperial":"17 - 20"}','','B1u4zgqE7','images-list-dogs\German-Pinscher.jpg','1'),

(null,'115','German Shepherd Dog','German Shepherd Dog','Herding - Guard dog','Herding - Guard dog','Herding','Herding','10 - 13 years','Alert - Loyal - Obedient - Curious - Confident - Intelligent - Watchful - Courageous','Alert - Loyal - Obedient - Curious - Confident - Intelligent - Watchful - Courageous','','{"metric":"23 - 41","imperial":"50 - 90"}','{"metric":"56 - 66","imperial":"22 - 26"}','','SJyBfg5NX','images-list-dogs\German-Shepherd-Dog.jpg','1'),

(null,'116','German Shorthaired Pointer','German Shorthaired Pointer','General hunting','General hunting','Sporting','Sporting','12 - 14 years','Boisterous - Bold - Affectionate - Intelligent - Cooperative - Trainable','Boisterous - Bold - Affectionate - Intelligent - Cooperative - Trainable','','{"metric":"20 - 32","imperial":"45 - 70"}','{"metric":"53 - 64","imperial":"21 - 25"}','','SJqBMg5Nm','images-list-dogs\German-Shorthaired-Pointer.jpg','1'),

(null,'119','Giant Schnauzer','Giant Schnauzer','Herding - guarding','Herding - guarding','Working','Working','10 - 12 years','Strong Willed - Kind - Loyal - Intelligent - Dominant - Powerful','Strong Willed - Kind - Loyal - Intelligent - Dominant - Powerful','','{"metric":"29 - 41","imperial":"65 - 90"}','{"metric":"60 - 70","imperial":"23.5 - 27.5"}','','H1NIzlcV7','images-list-dogs\Giant-Schnauzer.jpg','1'),

(null,'120','Glen of Imaal Terrier','Glen of Imaal Terrier','Rid the home and farm of vermin - and hunt badger and fox','Rid the home and farm of vermin - and hunt badger and fox','Terrier','Terrier','12 - 15 years','Spirited - Agile - Loyal - Gentle - Active - Courageous','Spirited - Agile - Loyal - Gentle - Active - Courageous','','{"metric":"15 - 18","imperial":"32 - 40"}','{"metric":"32 - 36","imperial":"12.5 - 14"}','','H1oLMe94m','images-list-dogs\Glen-of-Imaal-Terrier.jpg','1'),

(null,'121','Golden Retriever','Golden Retriever','Retrieving','Retrieving','Sporting','Sporting','10 - 12 years','Intelligent - Kind - Reliable - Friendly - Trustworthy - Confident','Intelligent - Kind - Reliable - Friendly - Trustworthy - Confident','','{"metric":"25 - 34","imperial":"55 - 75"}','{"metric":"55 - 61","imperial":"21.5 - 24"}','','HJ7Pzg5EQ','images-list-dogs\Golden-Retriever.jpg','1'),

(null,'123','Gordon Setter','Gordon Setter','Find and point gamebirds','Find and point gamebirds','Sporting','Sporting','10 - 12 years','Fearless - Alert - Loyal - Confident - Gay - Eager','Fearless - Alert - Loyal - Confident - Gay - Eager','','{"metric":"20 - 36","imperial":"45 - 80"}','{"metric":"58 - 69","imperial":"23 - 27"}','','SJ5vzx5NX','images-list-dogs\Gordon-Setter.jpg','1'),

(null,'124','Great Dane','Great Dane','Hunting & holding boars - Guardian','Hunting & holding boars - Guardian','Working','Working','7 - 10 years','Friendly - Devoted - Reserved - Gentle - Confident - Loving','Friendly - Devoted - Reserved - Gentle - Confident - Loving','','{"metric":"50 - 86","imperial":"110 - 190"}','{"metric":"71 - 81","imperial":"28 - 32"}','','B1Edfl9NX','images-list-dogs\Great-Dane.jpg','1'),

(null,'125','Great Pyrenees','Great Pyrenees','Sheep guardian','Sheep guardian','Working','Working','10 - 12 years','Strong Willed - Fearless - Affectionate - Patient - Gentle - Confident','Strong Willed - Fearless - Affectionate - Patient - Gentle - Confident','','{"metric":"39 - 52","imperial":"85 - 115"}','{"metric":"64 - 81","imperial":"25 - 32"}','','B12uzg9V7','images-list-dogs\Great-Pyrenees.jpg','1'),

(null,'127','Greyhound','Greyhound','Coursing hares','Coursing hares','Hound','Hound','10 - 13 years','Affectionate - Athletic - Gentle - Intelligent - Quiet - Even Tempered','Affectionate - Athletic - Gentle - Intelligent - Quiet - Even Tempered','','{"metric":"23 - 32","imperial":"50 - 70"}','{"metric":"69 - 76","imperial":"27 - 30"}','','ryNYMx94X','images-list-dogs\Greyhound.jpg','1'),

(null,'128','Griffon Bruxellois','Griffon Bruxellois','Hunt and kill vermin in stables','Hunt and kill vermin in stables','','','10 – 15 years','Self-important - Inquisitive - Alert - Companionable - Sensitive - Watchful','Self-important - Inquisitive - Alert - Companionable - Sensitive - Watchful','','{"metric":"5","imperial":"12"}','{"metric":"23 - 28","imperial":"9 - 11"}','','ryoYGec4Q','images-list-dogs\Griffon-Bruxellois.jpg','1'),

(null,'129','Harrier','Harrier','Hunting hares by trailing them','Hunting hares by trailing them','Hound','Hound','12 - 15 years','Outgoing - Friendly - Cheerful - Sweet-Tempered - Tolerant - Active','Outgoing - Friendly - Cheerful - Sweet-Tempered - Tolerant - Active','','{"metric":"18 - 27","imperial":"40 - 60"}','{"metric":"46 - 56","imperial":"18 - 22"}','','B1IcfgqE7','images-list-dogs\Harrier.jpg','1'),

(null,'130','Havanese','Havanese','Companionship','Companionship','Toy','Toy','14 - 15 years','Affectionate - Responsive - Playful - Companionable - Gentle - Intelligent','Affectionate - Responsive - Playful - Companionable - Gentle - Intelligent','','{"metric":"3 - 6","imperial":"7 - 13"}','{"metric":"22 - 29","imperial":"8.5 - 11.5"}','','rkXiGl9V7','images-list-dogs\Havanese.jpg','1'),

(null,'134','Irish Setter','Irish Setter','Bird setting - retrieving','Bird setting - retrieving','Sporting','Sporting','10 - 11 years','Affectionate - Energetic - Lively - Independent - Playful - Companionable','Affectionate - Energetic - Lively - Independent - Playful - Companionable','','{"metric":"16 - 32","imperial":"35 - 70"}','{"metric":"61 - 69","imperial":"24 - 27"}','','S1osGeqVm','images-list-dogs\Irish-Setter.jpg','1'),

(null,'135','Irish Terrier','Irish Terrier','','','Terrier','Terrier','12 - 16 years','Respectful - Lively - Intelligent - Dominant - Protective - Trainable','Respectful - Lively - Intelligent - Dominant - Protective - Trainable','','{"metric":"11 - 12","imperial":"25 - 27"}','{"metric":"46","imperial":"18"}','','By-hGecVX','images-list-dogs\Irish-Terrier.jpg','1'),

(null,'137','Irish Wolfhound','Irish Wolfhound','Coursing wolves - elk','Coursing wolves - elk','Hound','Hound','6 - 8 years','Sweet-Tempered - Loyal - Dignified - Patient - Thoughtful - Generous','Sweet-Tempered - Loyal - Dignified - Patient - Thoughtful - Generous','','{"metric":"48 - 82","imperial":"105 - 180"}','{"metric":"76 - 89","imperial":"30 - 35"}','','Hyd2zgcEX','images-list-dogs\Irish-Wolfhound.jpg','1'),

(null,'138','Italian Greyhound','Italian Greyhound','Lapdog','Lapdog','Toy','Toy','12 - 15 years','Mischievous - Affectionate - Agile - Athletic - Companionable - Intelligent','Mischievous - Affectionate - Agile - Athletic - Companionable - Intelligent','','{"metric":"3 - 7","imperial":"7 - 15"}','{"metric":"33 - 38","imperial":"13 - 15"}','','SJAnzg9NX','images-list-dogs\Italian-Greyhound.jpg','1'),

(null,'140','Japanese Chin','Japanese Chin','Lapdog','Lapdog','Toy','Toy','12 - 14 years','Alert - Loyal - Independent - Intelligent - Loving - Cat-like','Alert - Loyal - Independent - Intelligent - Loving - Cat-like','','{"metric":"2 - 4","imperial":"4 - 9"}','{"metric":"20 - 28","imperial":"8 - 11"}','','r1H6feqEm','images-list-dogs\Japanese-Chin.jpg','1'),

(null,'141','Japanese Spitz','Japanese Spitz','Companion','Companion','','','10 – 16 years','Affectionate - Obedient - Playful - Companionable - Intelligent - Proud','Affectionate - Obedient - Playful - Companionable - Intelligent - Proud','','{"metric":"7 - 9","imperial":"15 - 19"}','{"metric":"30 - 38","imperial":"12 - 15"}','','HksaMxqNX','images-list-dogs\Japanese-Spitz.jpg','1'),

(null,'142','Keeshond','Keeshond','Barge watchdog','Barge watchdog','Non-Sporting','Non-Sporting','12 - 15 years','Agile - Obedient - Playful - Quick - Sturdy - Bright','Agile - Obedient - Playful - Quick - Sturdy - Bright','','{"metric":"16 - 20","imperial":"35 - 45"}','{"metric":"43 - 46","imperial":"17 - 18"}','','S1GAGg9Vm','images-list-dogs\Keeshond.jpg','1'),

(null,'144','Komondor','Komondor','Sheep guardian','Sheep guardian','Working','Working','10 - 12 years','Steady - Fearless - Affectionate - Independent - Gentle - Calm','Steady - Fearless - Affectionate - Independent - Gentle - Calm','','{"metric":"36 - 45","imperial":"80 - 100"}','{"metric":"65 - 70","imperial":"25.5 - 27.5"}','','Bko0fl547','images-list-dogs\Komondor.jpg','1'),

(null,'145','Kooikerhondje','Kooikerhondje','Luring ducks into traps - "tolling"','Luring ducks into traps - "tolling"','Sporting','Sporting','12 - 15 years','Benevolent - Agile - Alert - Intelligent - Active - Territorial','Benevolent - Agile - Alert - Intelligent - Active - Territorial','','{"metric":"9 - 14","imperial":"20 - 30"}','{"metric":"36 - 41","imperial":"14 - 16"}','','kOMy84GQE','images-list-dogs\Kooikerhondje.jpg','1'),

(null,'147','Kuvasz','Kuvasz','Guardian - hunting large game','Guardian - hunting large game','Working','Working','8 - 10 years','Clownish - Loyal - Patient - Independent - Intelligent - Protective','Clownish - Loyal - Patient - Independent - Intelligent - Protective','','{"metric":"32 - 52","imperial":"70 - 115"}','{"metric":"66 - 76","imperial":"26 - 30"}','','BykZ7ecVX','images-list-dogs\Kuvasz.jpg','1'),

(null,'149','Labrador Retriever','Labrador Retriever','Water retrieving','Water retrieving','Sporting','Sporting','10 - 13 years','Kind - Outgoing - Agile - Gentle - Intelligent - Trusting - Even Tempered','Kind - Outgoing - Agile - Gentle - Intelligent - Trusting - Even Tempered','','{"metric":"25 - 36","imperial":"55 - 80"}','{"metric":"55 - 62","imperial":"21.5 - 24.5"}','','B1uW7l5VX','images-list-dogs\Labrador-Retriever.jpg','1'),

(null,'151','Lagotto Romagnolo','Lagotto Romagnolo','Water retrieval dog in the marshes of Romagna','Water retrieval dog in the marshes of Romagna','Sporting','Sporting','14 - 16 years','Keen - Loyal - Companionable - Loving - Active - Trainable','Keen - Loyal - Companionable - Loving - Active - Trainable','','{"metric":"11 - 16","imperial":"24 - 35"}','{"metric":"41 - 48","imperial":"16 - 19"}','','ryzzmgqE7','images-list-dogs\Lagotto-Romagnolo.jpg','1'),

(null,'153','Lancashire Heeler','Lancashire Heeler','Cattle herding - Ratting - Driving cattle to market.','Cattle herding - Ratting - Driving cattle to market.','','','12 – 15 years','Clever - Friendly - Alert - Intelligent','Clever - Friendly - Alert - Intelligent','','{"metric":"3 - 6","imperial":"6 - 13"}','{"metric":"25 - 30","imperial":"10 - 12"}','','S1RGml5Em','images-list-dogs\Lancashire-Heeler.jpg','1'),

(null,'155','Leonberger','Leonberger','Guardian - appearance.','Guardian - appearance.','Working','Working','6 - 8 years','Obedient - Fearless - Loyal - Companionable - Adaptable - Loving','Obedient - Fearless - Loyal - Companionable - Adaptable - Loving','','{"metric":"54 - 77","imperial":"120 - 170"}','{"metric":"65 - 80","imperial":"25.5 - 31.5"}','','ByrmQlqVm','images-list-dogs\Leonberger.jpg','1'),

(null,'156','Lhasa Apso','Lhasa Apso','Guarding inside the home - companion','Guarding inside the home - companion','Non-Sporting','Non-Sporting','12 - 15 years','Steady - Fearless - Friendly - Devoted - Assertive - Spirited - Energetic - Lively - Alert - Obedient - Playful - Intelligent','Steady - Fearless - Friendly - Devoted - Assertive - Spirited - Energetic - Lively - Alert - Obedient - Playful - Intelligent','','{"metric":"5 - 8","imperial":"12 - 18"}','{"metric":"25 - 28","imperial":"10 - 11"}','','SJp7Qe5EX','images-list-dogs\Lhasa-Apso.jpg','1'),

(null,'161','Maltese','Maltese','Lapdog','Lapdog','Toy','Toy','15 - 18 years','Playful - Docile - Fearless - Affectionate - Sweet-Tempered - Lively - Responsive - Easygoing - Gentle - Intelligent - Active','Playful - Docile - Fearless - Affectionate - Sweet-Tempered - Lively - Responsive - Easygoing - Gentle - Intelligent - Active','','{"metric":"2 - 3","imperial":"4 - 7"}','{"metric":"20 - 25","imperial":"8 - 10"}','','B1SV7gqN7','images-list-dogs\Maltese.jpg','1'),

(null,'165','Miniature American Shepherd','Miniature American Shepherd','','','Herding','Herding','12 - 15 years','Energetic - Loyal - Intelligent - Trainable','Energetic - Loyal - Intelligent - Trainable','','{"metric":"9 - 18","imperial":"20 - 40"}','{"metric":"33 - 46","imperial":"13 - 18"}','','BkHHQgcN7','images-list-dogs\Miniature-American-Shepherd.jpg','1'),

(null,'167','Miniature Pinscher','Miniature Pinscher','Small vermin hunting','Small vermin hunting','Toy','Toy','15 years','Clever - Outgoing - Friendly - Energetic - Responsive - Playful','Clever - Outgoing - Friendly - Energetic - Responsive - Playful','','{"metric":"4 - 5","imperial":"8 - 11"}','{"metric":"25 - 32","imperial":"10 - 12.5"}','','Hy3H7g94X','images-list-dogs\Miniature-Pinscher.jpg','1'),

(null,'168','Miniature Schnauzer','Miniature Schnauzer','Ratting','Ratting','Terrier','Terrier','12 - 14 years','Fearless - Friendly - Spirited - Alert - Obedient - Intelligent','Fearless - Friendly - Spirited - Alert - Obedient - Intelligent','','{"metric":"5 - 9","imperial":"11 - 20"}','{"metric":"30 - 36","imperial":"12 - 14"}','','SJIUQl9NX','images-list-dogs\Miniature-Schnauzer.jpg','1'),

(null,'171','Newfoundland','Newfoundland','All purpose water dog - fishing aid','All purpose water dog - fishing aid','Working','Working','8 - 10 years','Sweet-Tempered - Gentle - Trainable','Sweet-Tempered - Gentle - Trainable','','{"metric":"45 - 68","imperial":"100 - 150"}','{"metric":"66 - 71","imperial":"26 - 28"}','','Sk4DXl54m','images-list-dogs\Newfoundland.jpg','1'),

(null,'172','Norfolk Terrier','Norfolk Terrier','Ratting - fox bolting','Ratting - fox bolting','Terrier','Terrier','12 - 15 years','Self-confidence - Fearless - Spirited - Companionable - Happy - Lovable','Self-confidence - Fearless - Spirited - Companionable - Happy - Lovable','','{"metric":"5 - 5","imperial":"11 - 12"}','{"metric":"23 - 25","imperial":"9 - 10"}','','B1ADQg94X','images-list-dogs\Norfolk-Terrier.jpg','1'),

(null,'176','Norwich Terrier','Norwich Terrier','Ratting - fox bolting','Ratting - fox bolting','Terrier','Terrier','12 - 15 years','Hardy - Affectionate - Energetic - Sensitive - Intelligent','Hardy - Affectionate - Energetic - Sensitive - Intelligent','','{"metric":"5 - 5","imperial":"11 - 12"}','{"metric":"25","imperial":"10"}','','BkgKXlqE7','images-list-dogs\Norwich-Terrier.jpg','1'),

(null,'177','Nova Scotia Duck Tolling Retriever','Nova Scotia Duck Tolling Retriever','','','Sporting','Sporting','12 - 14 years','Outgoing - Alert - Patient - Intelligent - Loving','Outgoing - Alert - Patient - Intelligent - Loving','','{"metric":"16 - 23","imperial":"35 - 50"}','{"metric":"43 - 53","imperial":"17 - 21"}','','SyYtQe5V7','images-list-dogs\Nova-Scotia-Duck-Tolling-Retriever.jpg','1'),

(null,'178','Old English Sheepdog','Old English Sheepdog','Driving sheep - cattle','Driving sheep - cattle','Herding','Herding','10 - 12 years','Sociable - Bubbly - Playful - Adaptable - Intelligent - Loving','Sociable - Bubbly - Playful - Adaptable - Intelligent - Loving','','{"metric":"27 - 45","imperial":"60 - 100"}','{"metric":"53","imperial":"21"}','','HkZ57lq4m','images-list-dogs\Old-English-Sheepdog.jpg','1'),

(null,'179','Olde English Bulldogge','Olde English Bulldogge','','','','','9 – 14 years','Friendly - Alert - Confident - Loving - Courageous - Strong','Friendly - Alert - Confident - Loving - Courageous - Strong','','{"metric":"NaN","imperial":"65 �\u20ac\u201c 85"}','{"metric":"38 - 48","imperial":"15 - 19"}','','B1d5me547','images-list-dogs\Olde-English-Bulldogge.jpg','1'),

(null,'181','Papillon','Papillon','Lapdog','Lapdog','Toy','Toy','13 - 17 years','Hardy - Friendly - Energetic - Alert - Intelligent - Happy','Hardy - Friendly - Energetic - Alert - Intelligent - Happy','','{"metric":"1 - 5","imperial":"3 - 12"}','{"metric":"20 - 28","imperial":"8 - 11"}','','SkJj7e547','images-list-dogs\Papillon.jpg','1'),

(null,'183','Pekingese','Pekingese','Lapdog','Lapdog','Toy','Toy','14 - 18 years','Opinionated - Good-natured - Stubborn - Affectionate - Aggressive - Intelligent','Opinionated - Good-natured - Stubborn - Affectionate - Aggressive - Intelligent','','{"metric":"6","imperial":"14"}','{"metric":"15 - 23","imperial":"6 - 9"}','','ByIiml9Nm','images-list-dogs\Pekingese.jpg','1'),

(null,'184','Pembroke Welsh Corgi','Pembroke Welsh Corgi','Driving stock to market in northern Wales','Driving stock to market in northern Wales','Herding','Herding','12 - 14 years','Tenacious - Outgoing - Friendly - Bold - Playful - Protective','Tenacious - Outgoing - Friendly - Bold - Playful - Protective','','{"metric":"11 - 14","imperial":"25 - 30"}','{"metric":"25 - 30","imperial":"10 - 12"}','','rJ6iQeqEm','images-list-dogs\Pembroke-Welsh-Corgi.jpg','1'),

(null,'185','Perro de Presa Canario','Perro de Presa Canario','','','Working','Working','10 - 12 years','Strong Willed - Suspicious - Gentle - Dominant - Calm','Strong Willed - Suspicious - Gentle - Dominant - Calm','','{"metric":"40 - 50","imperial":"88 - 110"}','{"metric":"56 - 65","imperial":"22 - 25.5"}','','S1V3Qeq4X','images-list-dogs\Perro-de-Presa-Canario.jpg','1'),

(null,'188','Pharaoh Hound','Pharaoh Hound','Hunting rabbits','Hunting rabbits','Hound','Hound','12 - 14 years','Affectionate - Sociable - Playful - Intelligent - Active - Trainable','Affectionate - Sociable - Playful - Intelligent - Active - Trainable','','{"metric":"18 - 27","imperial":"40 - 60"}','{"metric":"53 - 64","imperial":"21 - 25"}','','Byz6mgqEQ','images-list-dogs\Pharaoh-Hound.jpg','1'),

(null,'189','Plott','Plott','Hunting big-game like Boar.','Hunting big-game like Boar.','Hound','Hound','12 - 14 years','Bold - Alert - Loyal - Intelligent','Bold - Alert - Loyal - Intelligent','','{"metric":"18 - 27","imperial":"40 - 60"}','{"metric":"51 - 64","imperial":"20 - 25"}','','B1i67l5VQ','images-list-dogs\Plott.jpg','1'),

(null,'193','Pomeranian','Pomeranian','Companion','Companion','Toy','Toy','15 years','Extroverted - Friendly - Sociable - Playful - Intelligent - Active','Extroverted - Friendly - Sociable - Playful - Intelligent - Active','','{"metric":"1 - 3","imperial":"3 - 7"}','{"metric":"20 - 30","imperial":"8 - 12"}','','HJd0XecNX','images-list-dogs\Pomeranian.jpg','1'),

(null,'196','Poodle  -Miniature-','Poodle  -Miniature-','','','','','12 – 15 years','','','','{"metric":"7 - 8","imperial":"15 - 17"}','{"metric":"28 - 38","imperial":"11 - 15"}','','Hkxk4ecVX','images-list-dogs\Poodle---Miniature-.jpg','1'),

(null,'197','Poodle  -Toy-','Poodle  -Toy-','','','','','18 years','','','','{"metric":"3 - 4","imperial":"6 - 9"}','{"metric":"23 - 28","imperial":"9 - 11"}','','rJFJVxc4m','images-list-dogs\Poodle---Toy-.jpg','1'),

(null,'201','Pug','Pug','Lapdog','Lapdog','Toy','Toy','12 - 14 years','Docile - Clever - Charming - Stubborn - Sociable - Playful - Quiet - Attentive','Docile - Clever - Charming - Stubborn - Sociable - Playful - Quiet - Attentive','','{"metric":"6 - 8","imperial":"14 - 18"}','{"metric":"25 - 30","imperial":"10 - 12"}','','HyJvcl9N7','images-list-dogs\Pug.jpg','1'),

(null,'204','Puli','Puli','Herding','Herding','Herding','Herding','12 - 16 Years years','Energetic - Agile - Loyal - Obedient - Intelligent - Faithful','Energetic - Agile - Loyal - Obedient - Intelligent - Faithful','','{"metric":"11 - 16","imperial":"25 - 35"}','{"metric":"41 - 43","imperial":"16 - 17"}','','ryPgVl5N7','images-list-dogs\Puli.jpg','1'),

(null,'205','Pumi','Pumi','','','Herding','Herding','13 - 15 years','Lively - Reserved - Intelligent - Active - Protective - Vocal','Lively - Reserved - Intelligent - Active - Protective - Vocal','','{"metric":"8 - 15","imperial":"18 - 33"}','{"metric":"38 - 47","imperial":"15 - 18.5"}','','SyRe4xcN7','images-list-dogs\Pumi.jpg','1'),

(null,'207','Rat Terrier','Rat Terrier','','','Terrier','Terrier','12 - 18 years','Affectionate - Lively - Inquisitive - Alert - Intelligent - Loving','Affectionate - Lively - Inquisitive - Alert - Intelligent - Loving','','{"metric":"4 - 11","imperial":"8 - 25"}','{"metric":"25 - 33","imperial":"10 - 13"}','','HkXWNl9E7','images-list-dogs\Rat-Terrier.jpg','1'),

(null,'208','Redbone Coonhound','Redbone Coonhound','Hunting raccoon - deer - bear - and cougar.','Hunting raccoon - deer - bear - and cougar.','Hound','Hound','10 - 12 years','Affectionate - Energetic - Independent - Companionable - Familial - Unflappable','Affectionate - Energetic - Independent - Companionable - Familial - Unflappable','','{"metric":"20 - 36","imperial":"45 - 80"}','{"metric":"53 - 69","imperial":"21 - 27"}','','HJMzEl5N7','images-list-dogs\Redbone-Coonhound.jpg','1'),

(null,'209','Rhodesian Ridgeback','Rhodesian Ridgeback','Big game hunting - guarding','Big game hunting - guarding','Hound','Hound','10 - 12 years','Strong Willed - Mischievous - Loyal - Dignified - Sensitive - Intelligent','Strong Willed - Mischievous - Loyal - Dignified - Sensitive - Intelligent','','{"metric":"34 - 36","imperial":"75 - 80"}','{"metric":"61 - 69","imperial":"24 - 27"}','','By9zNgqE7','images-list-dogs\Rhodesian-Ridgeback.jpg','1'),

(null,'210','Rottweiler','Rottweiler','Cattle drover - guardian - draft','Cattle drover - guardian - draft','Working','Working','8 - 10 years','Steady - Good-natured - Fearless - Devoted - Alert - Obedient - Confident - Self-assured - Calm - Courageous','Steady - Good-natured - Fearless - Devoted - Alert - Obedient - Confident - Self-assured - Calm - Courageous','','{"metric":"34 - 50","imperial":"75 - 110"}','{"metric":"56 - 69","imperial":"22 - 27"}','','r1xXEgcNX','images-list-dogs\Rottweiler.jpg','1'),

(null,'211','Russian Toy','Russian Toy','','','Toy','Toy','10 - 12 years','','','','{"metric":"1 - 3","imperial":"3 - 6"}','{"metric":"19 - 27","imperial":"7.5 - 10.5"}','','HkP7Vxc4Q','images-list-dogs\Russian-Toy.jpg','1'),

(null,'212','Saint Bernard','Saint Bernard','Draft - search - rescue','Draft - search - rescue','Working','Working','7 - 10 years','Friendly - Lively - Gentle - Watchful - Calm','Friendly - Lively - Gentle - Watchful - Calm','','{"metric":"59 - 82","imperial":"130 - 180"}','{"metric":"65 - 70","imperial":"25.5 - 27.5"}','','_Qf9nfRzL','images-list-dogs\Saint-Bernard.jpg','1'),

(null,'213','Saluki','Saluki','Coursing gazelle and hare','Coursing gazelle and hare','Hound','Hound','12 - 14 years','Aloof - Reserved - Intelligent - Quiet','Aloof - Reserved - Intelligent - Quiet','','{"metric":"16 - 29","imperial":"35 - 65"}','{"metric":"58 - 71","imperial":"23 - 28"}','','fjFIuehNo','images-list-dogs\Saluki.jpg','1'),

(null,'214','Samoyed','Samoyed','Herding reindeer - guardian - draft','Herding reindeer - guardian - draft','Working','Working','12 - 14 years','Stubborn - Friendly - Sociable - Lively - Alert - Playful','Stubborn - Friendly - Sociable - Lively - Alert - Playful','','{"metric":"23 - 27","imperial":"50 - 60"}','{"metric":"48 - 60","imperial":"19 - 23.5"}','','S1T8Ee9Nm','images-list-dogs\Samoyed.jpg','1'),

(null,'216','Schipperke','Schipperke','Barge watchdog','Barge watchdog','Non-Sporting','Non-Sporting','13 - 15 years','Fearless - Agile - Curious - Independent - Confident - Faithful','Fearless - Agile - Curious - Independent - Confident - Faithful','','{"metric":"5 - 7","imperial":"10 - 16"}','{"metric":"25 - 33","imperial":"10 - 13"}','','SyBvVgc47','images-list-dogs\Schipperke.jpg','1'),

(null,'218','Scottish Deerhound','Scottish Deerhound','Coursing deer','Coursing deer','Hound','Hound','8 - 10 years','Docile - Friendly - Dignified - Gentle','Docile - Friendly - Dignified - Gentle','','{"metric":"32 - 59","imperial":"70 - 130"}','{"metric":"71 - 81","imperial":"28 - 32"}','','SkNjqx9NQ','images-list-dogs\Scottish-Deerhound.jpg','1'),

(null,'219','Scottish Terrier','Scottish Terrier','Vermin hunting','Vermin hunting','Terrier','Terrier','11 - 13 years','Feisty - Alert - Independent - Playful - Quick - Self-assured','Feisty - Alert - Independent - Playful - Quick - Self-assured','','{"metric":"8 - 10","imperial":"18 - 22"}','{"metric":"25","imperial":"10"}','','Bklnce5NX','images-list-dogs\Scottish-Terrier.jpg','1'),

(null,'221','Shetland Sheepdog','Shetland Sheepdog','Sheep herding','Sheep herding','Herding','Herding','12 - 14 years','Affectionate - Lively - Responsive - Alert - Loyal - Reserved - Playful - Gentle - Intelligent - Active - Trainable - Strong','Affectionate - Lively - Responsive - Alert - Loyal - Reserved - Playful - Gentle - Intelligent - Active - Trainable - Strong','','{"metric":"14","imperial":"30"}','{"metric":"33 - 41","imperial":"13 - 16"}','','rJa29l9E7','images-list-dogs\Shetland-Sheepdog.jpg','1'),

(null,'222','Shiba Inu','Shiba Inu','Hunting in the mountains of Japan - Alert Watchdog','Hunting in the mountains of Japan - Alert Watchdog','Non-Sporting','Non-Sporting','12 - 16 years','Charming - Fearless - Keen - Alert - Confident - Faithful','Charming - Fearless - Keen - Alert - Confident - Faithful','','{"metric":"8 - 10","imperial":"17 - 23"}','{"metric":"34 - 42","imperial":"13.5 - 16.5"}','','Zn3IjPX3f','images-list-dogs\Shiba-Inu.jpg','1'),

(null,'223','Shih Tzu','Shih Tzu','Lapdog','Lapdog','Toy','Toy','10 - 18 years','Clever - Spunky - Outgoing - Friendly - Affectionate - Lively - Alert - Loyal - Independent - Playful - Gentle - Intelligent - Happy - Active - Courageous','Clever - Spunky - Outgoing - Friendly - Affectionate - Lively - Alert - Loyal - Independent - Playful - Gentle - Intelligent - Happy - Active - Courageous','','{"metric":"4 - 7","imperial":"9 - 16"}','{"metric":"20 - 28","imperial":"8 - 11"}','','BkrJjgcV7','images-list-dogs\Shih-Tzu.jpg','1'),

(null,'225','Shiloh Shepherd','Shiloh Shepherd','Swimming - Carrying backpacks - Pulling carts or sleds','Swimming - Carrying backpacks - Pulling carts or sleds','','','9 – 14 years','Outgoing - Loyal - Companionable - Gentle - Loving - Trainable','Outgoing - Loyal - Companionable - Gentle - Loving - Trainable','','{"metric":"54 - 64","imperial":"120 - 140"}','{"metric":"66 - 76","imperial":"26 - 30"}','','SJJxjecEX','images-list-dogs\Shiloh-Shepherd.jpg','1'),

(null,'226','Siberian Husky','Siberian Husky','Sled pulling','Sled pulling','Working','Working','12 years','Outgoing - Friendly - Alert - Gentle - Intelligent','Outgoing - Friendly - Alert - Gentle - Intelligent','','{"metric":"16 - 27","imperial":"35 - 60"}','{"metric":"51 - 60","imperial":"20 - 23.5"}','','S17ZilqNm','images-list-dogs\Siberian-Husky.jpg','1'),

(null,'228','Silky Terrier','Silky Terrier','Small vermin hunting - companionship','Small vermin hunting - companionship','Toy','Toy','12 - 15 years','Friendly - Responsive - Inquisitive - Alert - Quick - Joyful','Friendly - Responsive - Inquisitive - Alert - Quick - Joyful','','{"metric":"4 - 5","imperial":"8 - 10"}','{"metric":"23 - 25","imperial":"9 - 10"}','','ByzGsl5Nm','images-list-dogs\Silky-Terrier.jpg','1'),

(null,'232','Smooth Fox Terrier','Smooth Fox Terrier','Fox bolting','Fox bolting','Terrier','Terrier','12 - 14 years','Fearless - Affectionate - Alert - Playful - Intelligent - Active','Fearless - Affectionate - Alert - Playful - Intelligent - Active','','{"metric":"NaN - 8","imperial":"up - 18"}','{"metric":"39","imperial":"15.5"}','','Syszjx9Em','images-list-dogs\Smooth-Fox-Terrier.jpg','1'),

(null,'233','Soft Coated Wheaten Terrier','Soft Coated Wheaten Terrier','Vermin hunting - guarding - all-around farm helper','Vermin hunting - guarding - all-around farm helper','Terrier','Terrier','12 - 15 years','Affectionate - Spirited - Energetic - Playful - Intelligent - Faithful','Affectionate - Spirited - Energetic - Playful - Intelligent - Faithful','','{"metric":"14 - 18","imperial":"30 - 40"}','{"metric":"41 - 46","imperial":"16 - 18"}','','HJHmix5NQ','images-list-dogs\Soft-Coated-Wheaten-Terrier.jpg','1'),

(null,'235','Spanish Water Dog','Spanish Water Dog','Herding flocks of sheep and goats from one pasture to another','Herding flocks of sheep and goats from one pasture to another','Sporting','Sporting','12 - 15 years','Trainable - Diligent - Affectionate - Loyal - Athletic - Intelligent','Trainable - Diligent - Affectionate - Loyal - Athletic - Intelligent','','{"metric":"14 - 23","imperial":"30 - 50"}','{"metric":"41 - 51","imperial":"16 - 20"}','','HJf4jl9VX','images-list-dogs\Spanish-Water-Dog.jpg','1'),

(null,'236','Spinone Italiano','Spinone Italiano','','','Sporting','Sporting','10 - 12 years','Docile - Friendly - Affectionate - Loyal - Patient - Gentle','Docile - Friendly - Affectionate - Loyal - Patient - Gentle','','{"metric":"28 - 39","imperial":"61 - 85"}','{"metric":"57 - 70","imperial":"22.5 - 27.5"}','','rk5Eoe5Nm','images-list-dogs\Spinone-Italiano.jpg','1'),

(null,'238','Staffordshire Bull Terrier','Staffordshire Bull Terrier','','','Terrier','Terrier','12 - 14 years','Reliable - Fearless - Bold - Affectionate - Loyal - Intelligent - Courageous','Reliable - Fearless - Bold - Affectionate - Loyal - Intelligent - Courageous','','{"metric":"11 - 17","imperial":"24 - 38"}','{"metric":"36 - 41","imperial":"14 - 16"}','','H1zSie9V7','images-list-dogs\Staffordshire-Bull-Terrier.jpg','1'),

(null,'239','Standard Schnauzer','Standard Schnauzer','Ratting - guarding','Ratting - guarding','Working','Working','13 - 15 years','Trainable - Good-natured - Devoted - Lively - Playful - Intelligent','Trainable - Good-natured - Devoted - Lively - Playful - Intelligent','','{"metric":"14 - 23","imperial":"30 - 50"}','{"metric":"44 - 50","imperial":"17.5 - 19.5"}','','tmzeu6ID_','images-list-dogs\Standard-Schnauzer.jpg','1'),

(null,'242','Swedish Vallhund','Swedish Vallhund','','','Herding','Herding','12 - 14 years','Fearless - Friendly - Energetic - Alert - Intelligent - Watchful','Fearless - Friendly - Energetic - Alert - Intelligent - Watchful','','{"metric":"9 - 14","imperial":"20 - 30"}','{"metric":"29 - 34","imperial":"11.5 - 13.5"}','','HJ-Dix94Q','images-list-dogs\Swedish-Vallhund.jpg','1'),

(null,'243','Thai Ridgeback','Thai Ridgeback','','','Hound','Hound','10 - 12 years','Protective - Loyal - Independent - Intelligent - Loving - Familial','Protective - Loyal - Independent - Intelligent - Loving - Familial','','{"metric":"16 - 25","imperial":"35 - 55"}','{"metric":"51 - 61","imperial":"20 - 24"}','','zv89hR-O8','images-list-dogs\Thai-Ridgeback.jpg','1'),

(null,'244','Tibetan Mastiff','Tibetan Mastiff','','','Working','Working','10 - 14 years','Strong Willed - Tenacious - Aloof - Stubborn - Intelligent - Protective','Strong Willed - Tenacious - Aloof - Stubborn - Intelligent - Protective','','{"metric":"39 - 64","imperial":"85 - 140"}','{"metric":"61 - 66","imperial":"24 - 26"}','','SkM9sec47','images-list-dogs\Tibetan-Mastiff.jpg','1'),

(null,'245','Tibetan Spaniel','Tibetan Spaniel','','','Non-Sporting','Non-Sporting','12 - 15 years','Willful - Aloof - Assertive - Independent - Playful - Intelligent - Happy','Willful - Aloof - Assertive - Independent - Playful - Intelligent - Happy','','{"metric":"4 - 7","imperial":"9 - 15"}','{"metric":"25","imperial":"10"}','','Hyjcol947','images-list-dogs\Tibetan-Spaniel.jpg','1'),

(null,'246','Tibetan Terrier','Tibetan Terrier','Good luck charms - mascots - watchdogs - herding dogs - and companions','Good luck charms - mascots - watchdogs - herding dogs - and companions','Non-Sporting','Non-Sporting','12 - 15 years','Affectionate - Energetic - Amiable - Reserved - Gentle - Sensitive','Affectionate - Energetic - Amiable - Reserved - Gentle - Sensitive','','{"metric":"9 - 11","imperial":"20 - 24"}','{"metric":"36 - 43","imperial":"14 - 17"}','','6f5n_42mB','images-list-dogs\Tibetan-Terrier.jpg','1'),

(null,'248','Toy Fox Terrier','Toy Fox Terrier','','','Toy','Toy','12 - 15 years','Friendly - Spirited - Alert - Loyal - Playful - Intelligent','Friendly - Spirited - Alert - Loyal - Playful - Intelligent','','{"metric":"2 - 4","imperial":"4 - 9"}','{"metric":"20 - 28","imperial":"8 - 11"}','','B17ase9V7','images-list-dogs\Toy-Fox-Terrier.jpg','1'),

(null,'250','Treeing Walker Coonhound','Treeing Walker Coonhound','','','Hound','Hound','10 - 13 years','Clever - Affectionate - Confident - Intelligent - Loving - Trainable','Clever - Affectionate - Confident - Intelligent - Loving - Trainable','','{"metric":"20 - 36","imperial":"45 - 80"}','{"metric":"51 - 69","imperial":"20 - 27"}','','SkRpsgc47','images-list-dogs\Treeing-Walker-Coonhound.jpg','1'),

(null,'251','Vizsla','Vizsla','Pointing and trailing','Pointing and trailing','Sporting','Sporting','10 - 14 years','Affectionate - Energetic - Loyal - Gentle - Quiet','Affectionate - Energetic - Loyal - Gentle - Quiet','','{"metric":"23 - 29","imperial":"50 - 65"}','{"metric":"53 - 61","imperial":"21 - 24"}','','r1o0jx9Em','images-list-dogs\Vizsla.jpg','1'),

(null,'253','Weimaraner','Weimaraner','Large game trailing and versatile gundog','Large game trailing and versatile gundog','Sporting','Sporting','12 - 15 years','Steady - Aloof - Stubborn - Energetic - Alert - Intelligent - Powerful - Fast','Steady - Aloof - Stubborn - Energetic - Alert - Intelligent - Powerful - Fast','','{"metric":"25 - 41","imperial":"55 - 90"}','{"metric":"58 - 69","imperial":"23 - 27"}','','SyU12l9V7','images-list-dogs\Weimaraner.jpg','1'),

(null,'254','Welsh Springer Spaniel','Welsh Springer Spaniel','Flushing and retrieving birds','Flushing and retrieving birds','Sporting','Sporting','12 - 15 years','Stubborn - Friendly - Affectionate - Loyal - Playful - Active','Stubborn - Friendly - Affectionate - Loyal - Playful - Active','','{"metric":"16 - 25","imperial":"35 - 55"}','{"metric":"43 - 48","imperial":"17 - 19"}','','BJ1gnx5Vm','images-list-dogs\Welsh-Springer-Spaniel.jpg','1'),

(null,'256','West Highland White Terrier','West Highland White Terrier','Fox - badger - vermin hunting','Fox - badger - vermin hunting','Terrier','Terrier','15 - 20 years','Hardy - Friendly - Alert - Independent - Gay - Active - Courageous','Hardy - Friendly - Alert - Independent - Gay - Active - Courageous','','{"metric":"7 - 10","imperial":"15 - 22"}','{"metric":"25 - 28","imperial":"10 - 11"}','','Bkdx2g5Em','images-list-dogs\West-Highland-White-Terrier.jpg','1'),

(null,'257','Whippet','Whippet','Coursing - racing','Coursing - racing','Hound','Hound','12 - 15 years','Friendly - Affectionate - Lively - Gentle - Intelligent - Quiet','Friendly - Affectionate - Lively - Gentle - Intelligent - Quiet','','{"metric":"11 - 16","imperial":"25 - 35"}','{"metric":"46 - 56","imperial":"18 - 22"}','','Hyv-ne94m','images-list-dogs\Whippet.jpg','1'),

(null,'258','White Shepherd','White Shepherd','','','','','12 – 14 years','Self-confidence - Aloof - Fearless - Alert - Companionable - Eager','Self-confidence - Aloof - Fearless - Alert - Companionable - Eager','','{"metric":"27 - 39","imperial":"60 - 85"}','{"metric":"56 - 64","imperial":"22 - 25"}','','r14M3e9E7','images-list-dogs\White-Shepherd.jpg','1'),

(null,'259','Wire Fox Terrier','Wire Fox Terrier','Vermin hunting - fox bolting','Vermin hunting - fox bolting','','','13 – 14 years','Fearless - Friendly - Bold - Keen - Alert - Quick','Fearless - Friendly - Bold - Keen - Alert - Quick','','{"metric":"7 - 9","imperial":"15 - 19"}','{"metric":"33 - 41","imperial":"13 - 16"}','','SJ6f2g9EQ','images-list-dogs\Wire-Fox-Terrier.jpg','1'),

(null,'260','Wirehaired Pointing Griffon','Wirehaired Pointing Griffon','Gundog - "swamp-tromping" - Flushing - pointing - and retrieving water fowl & game birds','Gundog - "swamp-tromping" - Flushing - pointing - and retrieving water fowl & game birds','Sporting','Sporting','12 - 14 years','Loyal - Gentle - Vigilant - Trainable - Proud','Loyal - Gentle - Vigilant - Trainable - Proud','','{"metric":"20 - 32","imperial":"45 - 70"}','{"metric":"51 - 61","imperial":"20 - 24"}','','Bkam2l9Vm','images-list-dogs\Wirehaired-Pointing-Griffon.jpg','1'),

(null,'261','Wirehaired Vizsla','Wirehaired Vizsla','','','Sporting','Sporting','12 - 14 years','','','','{"metric":"20 - 29","imperial":"45 - 65"}','{"metric":"55 - 64","imperial":"21.5 - 25"}','','r1I4hl5Em','images-list-dogs\Wirehaired-Vizsla.jpg','1'),

(null,'262','Xoloitzcuintli','Xoloitzcuintli','','','Non-Sporting','Non-Sporting','12 - 14 years','Cheerful - Alert - Companionable - Intelligent - Protective - Calm','Cheerful - Alert - Companionable - Intelligent - Protective - Calm','','{"metric":"4 - 14","imperial":"9 - 31"}','{"metric":"25 - 58","imperial":"10 - 23"}','','HkNS3gqEm','images-list-dogs\Xoloitzcuintli.jpg','1'),

(null,'264','Yorkshire Terrier','Yorkshire Terrier','Small vermin hunting','Small vermin hunting','Toy','Toy','12 - 16 years','Bold - Independent - Confident - Intelligent - Courageous','Bold - Independent - Confident - Intelligent - Courageous','','{"metric":"2 - 3","imperial":"4 - 7"}','{"metric":"20 - 23","imperial":"8 - 9"}','','B12BnxcVQ','images-list-dogs\Yorkshire-Terrier.jpg','1')

