INSERT INTO breed_cat(id,
                      idName,
                      name, 
                      name_es,
                      cfa_url,
                      vetstreet_url,
                      vcahospitals_url,
                      temperament,
                      origin,
                      country_codes,
                      country_code,
                      description,
                      description_es,
                      life_span,
                      indoor,
                      lap,
                      alt_names, 
                      adaptability,
                      affection_level,
                      child_friendly,
                      dog_friendly,
                      energy_level,
                      grooming,
                      health_issues
                     ) VALUES

(null,
 'abys',
 'Abyssinian',
 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
 'http://www.vetstreet.com/cats/abyssinian',
 'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
 'Active - Energetic - Independent - Intelligent - Gentle',
 'Egypt',
 'EG',
 'EG',
 'The Abyssinian is easy to care for - and a joy to have in your home. Theyre affectionate cats and love both people and other animals.',
 '14 - 15',
 '0',
 '1',
 '',
 '5',
 '5',
 '3',
 '4',
 '1',
 '2',
 '5',
 '2',
 '5')
